### PR TITLE
Test Cases

### PR DESCRIPTION
**Pull request by claytondaley**
A first pass at tests for `sw_parser`

### CODE REVIEW

**Comment by claytondaley** [comment]
I haven't added any assertions yet, but the requests will at least error if something is horribly wrong.

**Comment by claytondaley** [comment]
Refactored for the new profile import location.

Also added a fixture (using my imported profile) to support tests that depend on a summoner and it's mons/runes/etc.  ATM I'm using it in tests in my "planner" module, but I figure it might be useful in other PRs/tests before my planner PR is ready.

**Comment by PeteAndersen** [comment]
I left this sitting for some time because the sw_parser app is being completely refactored into a different app. I didn't have any direction to give until now. In general I'd say copy the filesystem organization and testing approach I'm using in the [data_log app](https://github.com/PeteAndersen/swarfarm/tree/logs_redux/data_log/tests) (logs_redux branch, not yet in master).

* Fixtures should be added for required data to use during testing, like a user or bestiary data. Fixture should live in the same app as the test routines that rely on them. Don't rely on persistent test database with preloaded data.
* Only put objects that are required specifically by the tests in the fixtures. (use dumpdata `--pks` option). Nulling out foreign keys by hand is preferable - i.e. profile import does not need Skill objects, just Monster objects populated.
* Sample data should be stored in a separate file and not direct in code.

Since I've modified so much on the data log parsing side of things, I don't expect any work to update that for this PR. I'd prefer it be removed, and if you don't mind I will grab a lot of the sample data for usage in the new tests as I write them.

**Comment by claytondaley** [comment]
I was only trying to capture logs as a basis for the logs refactor.  If you have already captured alternative test cases, this duplicates that effort and can be closed.

**Comment by claytondaley** [comment]
... and of course if there's something worth preserving, feel free to do so.

**Comment by claytondaley** [comment]
P.S. While I agree with the use of fixtures (vs imports) in practice, I **strongly** suggest preserving the original JSON files.  Remember that the logs are tightly coupled to the summoner's profile.  I don't use fixtures often, but I assume that you'll create a massive headache if you were to make changes to the underlying models.  What happens to the fixtures?  Do you import, migrate, and regenerate them?

If you keep the JSON (and maybe a management command that generates fixtures), it's trivial to regenerate them any time the underlying data structures change.

**Comment by PeteAndersen** [comment]
Yes, all sample game data used in testing is original format since parsing the game data is what is being tested. Fixtures are only (at this moment) for a few instances of various bestiary models that back foreign keys required by the log data, such as monsters, summon scrolls, etc.

**Pull request closed without merging**
