### PR TITLE
Permalink filters

### LINKED ISSUE #16: Permalink to filter settings
https://swarfarm.com/feedback/376/

* Bestiary
* Monsters
* Runes

### PR DESCRIPTION
**Pull request by QuatZo**
* Bestiary
* Monsters
* Runes
* Artifacts

resolves #16

### CODE REVIEW

**Comment by PeteAndersen** [comment]
Updating the URL and then initializing the filters works great, but one problem I noticed with this approach is that the browser history is modified, but when using fwd/back buttons, nothing changes:

history_pollution

It might be better to use `replaceState()` instead of `pushState()` so the browser history isn't populated with many revs of filters, which avoids this problem and pressing the back button behaves the same as today.

**Comment by PeteAndersen** [comment]
For the bestiary filter specifically, the page parameter is included too. It works correctly, but I don't know if it's desired to include the page being viewed along with the filter set. I'll leave it up to you to decide.

**Comment by QuatZo** [comment]
> Updating the URL and then initializing the filters works great, but one problem I noticed with this approach is that the browser history is modified, but when using fwd/back buttons, nothing changes

I've changed that to `replaceState`. I could also implement event listener to reload content, but not changing `back` behaviour is probably the best option.

> For the bestiary filter specifically, the page parameter is included too. It works correctly, but I don't know if it's desired to include the page being viewed along with the filter set. I'll leave it up to you to decide.

It's needed so you can change pages. I mean, of course, I can delete it dynamically from URL (the same I do with `apply` parameter) after fetching data, but then whenever you refresh the browser, you go back to first page. I think there's nothing wrong with including it in params.

**Comment by PeteAndersen** [comment]
Although the values are being filtered according to the URL params, the sliders aren't updating correctly. Looks like they are being told to update before they're actually init by their own library:

image

**Comment by QuatZo** [comment]
> Although the values are being filtered according to the URL params, the sliders aren't updating correctly. Looks like they are being told to update before they're actually init by their own library:
> 
> image

Which file is this? I didn't see that in Runes, Artifacts & Monsters so I guess Bestiary? It's quite different than the others, I'm using params to filter form before any JS init from `bestiary/static/bestiary/js/bestiary.js`, not in `document.ready` as in other files. I'll check that and try to work around initial Bestiary data load.

**Comment by PeteAndersen** [comment]
Correct it was in bestiary

**Comment by QuatZo** [comment]
I've changed the way Bestiary loads. Previously when you changed page to Bestiary, you would get records quite fast but with all graphics loading one by one. Right now, it's pretty similar (if not the same) as for *Profile monsters*, *runes* & *artifacts* pages. Data starts downloading after whole page is ready to show - which means Sliders are already initialized.

I could just add data download from filters after initial Bestiary load, but it would mean double database hits.
bestiary

**Pull request merged**
