### PR TITLE
Implement BattleDungeonResult_V2

### LINKED ISSUE #128: Dungeon Results are not logged anymore (missing BattleDungeonResult_V2)
With the 5.2.7 (2020-03-13) game update, Com2uS implemented a new BattleDungeonResult packet that has quite a bit more information in it compared to the old one. This is presumably done to enable them to do some server-side processing in order to detect falsifyling dungeon runs (cheating).

The old BattleDungeonResult is - as it seems - no longer used and the newer one is not recognized by SWARFARM, which results in missing dungeon logs.

### PR DESCRIPTION
**Pull request by Lyrex**
This extends the work done in PR #130.
The patch should now correctly keep track of the rewards using the newly added changed_item_list.

Since I did not have logs for secret dungeons and materials, so this still needs some verification. Local tests were successful and indicated that rewards are correctly tracked again.

Fixes: #128

### CODE REVIEW

**Comment by PeteAndersen** [comment]
I had started collecting test data and modifying the test cases in my own branch, but I put them in here with yours. So far the only failing case is a monster drop. Do you want to add that?

**Comment by PeteAndersen** [comment]
Also, it seems that the BattleDungeonResult command is completely depreciated, so it can be removed from the code (schema, parse fn, etc)

**Comment by Lyrex** [comment]
After I found a secret dungeon today (thank god I didn't have to waste too much time on it) I implemented the missing tests and parsing.
Additionally I could implement the missing monster drop case that you provided a test case for.

Since secret dungeons seem to be a new drop type (`item_type` 30), I used a magic value for now in the parsing logic. We might want to refactor that into a proper constant, I just wasn't sure where to put it and how to name it.

According to your suggestion I removed the usages of the old and now deprecated `BattleDungeonResult` referenced too. I kept that in a singular commit to be able to revert it easily if necessary.

One thing you should verify again is the `test_monster_drop` test case. For me testing sometimes fails for it, sometimes it works. I checked the values in the debugger and ran the query against the database manually and from there everything seems fine. I'm not sure if that's just a test-environment-thing or if it's a real error.

**Comment by PeteAndersen** [comment]
Awesome, I pushed a few small changes and its good to merge! Thank you very much for taking care of this.

**Pull request merged**
